spring.application.name=sistema-ot

# Base de datos Local (desarrollo)
spring.datasource.url=jdbc:postgresql://localhost:5432/sistema_ot
spring.datasource.username=kabj_app
spring.datasource.password=KabjApp2026!

# Base de datos SUPABASE (producción - descomentar al desplegar)
# spring.datasource.url=jdbc:postgresql://db.jbbrbvqcxduczyowwbws.supabase.co:5432/postgres
# spring.datasource.username=postgres
# spring.datasource.password=KabjSistema2026Ot

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

server.port=8080

jwt.secret=kabj-sistema-ot-secret-key-2026-muy-larga-para-seguridad
jwt.expiration=36000000
cors.allowed-origin=http://localhost:5173