spring.application.name=sistema-ot

spring.datasource.url=jdbc:postgresql://localhost:5432/sistema_ot
spring.datasource.username=kabj_app
spring.datasource.password=KabjApp2026!

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

server.port=8080

jwt.secret=kabj-sistema-ot-secret-key-2026-muy-larga-para-seguridad
jwt.expiration=36000000

cors.allowed-origin=http://localhost:5173